DB_URL = mongodb Url
PORT = 5000
NODE_ENV = development

BCRYPT_SALT_ROUND=10

BCRYPT_SALT_ROUND=
JWT_ACCESS_SECRET = 
JWT_ACCESS_EXPIRES = 1d

SUPPER_ADMIN_EMAIL = "sarajit@gmail.com"
SUPPER_ADMIN_PASSWORD = 1234abcd

JWT_ACCESS_SECRET = MyNameIsSarajitMandal
JWT_ACCESS_EXPIRES = 1d
JWT_REFRESH_SECRET = MyNameIsSarajit
JWT_REFRESH_EXPIRES = 30d


# Google auth 
GOOGLE_CLIENT_ID = 278730067077-ap6ppfncdr2ui7213a
GOOGLE_CLIENT_SECRET = GOCSPX-
EXPRESS_SESSION_SECRET = express-session
GOOGLE_CALLBACK_URL = http://loccalhost:5000/api/v1/auth/google/callback

FRONTEND_URL = http://loccalhost:5173