DB_URL = mongodb Url
PORT = 5000
NODE_ENV = development

BCRYPT_SALT_ROUND=10

BCRYPT_SALT_ROUND=
JWT_ACCESS_SECRET = 
JWT_ACCESS_EXPIRES = 1d

SUPPER_ADMIN_EMAIL = "sarajit@gmail.com"
SUPPER_ADMIN_PASSWORD = 1234abcd